checks:
    javascript: true

build:
    dependencies:
        before:
            - npm install istanbul   # or add it as part of your package.json

    tests:
        override:
            -
                # command: 'istanbul cover --report clover test.js'
                # command: 'npm run test-scrutinizer'
                command: 'npm run test'
                coverage:
                    file: 'build/coverage/clover.xml'
                    format: 'clover'
